### PR TITLE
LRAC-5571 Update DXP to send groupId and channelId when creating experiments

### PR DESCRIPTION
**Pull request by darquesdev**
Thanks @andreldm and @gdss, go ahead and forward it to Brian if you consider It's ok.

cc: @cgoncas

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
This commit should fixe the problem https://github.com/liferay-echo/liferay-portal/pull/146/commits/cd6e09614157bc07b2039de8c4e3d2b1b97d4947

**Comment by andreldm** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andreldm** [comment]
Pull request submitted to https://github.com/andreldm/liferay-portal/pull/17. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andreldm** [comment]
Thanks David, I've rebased this pr with latest master.

**Pull request closed without merging**
