### PR TITLE
LRAC-5888 Pass initial middleware on create

### PR DESCRIPTION
**Pull request by fcodias**
https://issues.liferay.com/browse/LRAC-5888

### CODE REVIEW

**Comment by fcodias** [comment]
ci:test:sf

**Comment by fcodias** [comment]
ci:test:sf

**Comment by andreldm** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andreldm** [comment]
ci:forward

**Pull request closed without merging**
